### PR TITLE
Update to v8.2.2

### PR DESCRIPTION
**Pull request by ivmai**

### CODE REVIEW

**Comment by ivmai** [comment]
Hello @andyli, Is there any difficulty with this update?

**Comment by andyli** [comment]
Not really, just hadn't looked at it yet.

I noticed that is a new dll - cyggctba-1.dll. I guess it's an optional feature (i.e. people may depends on cyggccpp-1.dll but not cyggctba-1.dll), it would then be better to put it in its own libgctba1 package.

**Comment by ivmai** [comment]
cyggccpp.dll contains operator ::new() and GC_throw_bad_alloc().
cyggctba.dll contains only GC_throw_bad_alloc().
GC_throw_bad_alloc() is called by ::new() and other C++ bdwgc allocators on out of memory (before v8.2.0 ::new() returned NULL in such case which was not aligned well with the C++ standard).
Thus, C++ clients should link either with cyggccpp.dll or cyggctba.dll (not both) depending whether they want to redirect ::new to bdwgc or not.
Historically, clients are linked with cyggccpp.dll but some of newer clients might need to link with cyggctba.dll.
Both libraries are small in code size. I put cyggctba.dll to gccpp package to avoid increase of number of packages.
If you still think it is better to create libgctba1, I'm fine.

**Comment by andyli** [comment]
Thanks for the explanation. I think it make sense to group them together. Let's merge it as is.

**Comment by ivmai** [comment]
Thank you!

**Pull request merged**
